spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hybriddb
    username: hybrid_user
    password: hybrid_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    mongodb:
      uri: mongodb://localhost:27017/hybriddb
